<?php include('_includes/header.php'); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Descriptions</h1>
</div>
<div class="col-md-12">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>Id</th>
          <th>Subject</th>
          <th>Text</th>
          <th>User</th>
          <th>Date created</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($descriptions as $key => $value) {
          ?>
          <tr>
            <td><?php echo $value['id']; ?></td>
            <td><a href="/help/<?php echo $value['id']; ?>"><?php echo $value['subject']; ?></a></td>
            <td><?php echo substr(strip_tags(preg_replace('#<a.*?>.*?</a>#i', '', $value['description_body'])), 0, 150); ?></td>
            <td><?php echo $value['username']; ?></td>
            <td><?php echo $value['created_at']; ?></td>
            <td>
              <div class="btn-group mr-2">
                <a href="/help/descriptions/<?php echo $value['id']; ?>/edit" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="/help/descriptions/<?php echo $value['id']; ?>/delete" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</a>
              </div>
            </td>
          </tr>
          <?php
        } ?>
      </tbody>
    </table>
  </div>
  <hr class="mb-4">
</div>
<?php include('_includes/footer.php'); ?>
