<?php include('_includes/header.php'); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"><?php echo $desc['subject']; ?></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <?php if ($_SESSION['role'] == 2 || $_SESSION['uid'] == $desc['user_id']) {?>
      <div class="btn-group mr-2">
        <a href="/descriptions/<?php echo $desc['id']; ?>/edit" class="btn btn-sm btn-outline-secondary">Edit</a>
      </div>
    <?php  } ?>
  </div>
</div>
<div class="col-md-8">
  <div class="">
    <?php echo $desc['description_body']; ?>
  </div>

  <hr class="mb-4">

</div>
<?php include('_includes/footer.php'); ?>
