<?php include('_includes/header.php'); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Users</h1>
</div>
<div class="col-md-8">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Username</th>
          <th>Email</th>
          <th>Role</th>
          <th>Date created</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $key => $value) {
          ?>
          <tr>
            <td><?php echo $key+1; ?></td>
            <td><?php echo $value['username']; ?></td>
            <td><?php echo $value['email']; ?></td>
            <td>
              <?php if ($value['role_id'] == 1) {
                echo 'User';
              } elseif ($value['role_id'] == 2) {
                echo 'Admin';
              }  ?>
            </td>
            <td><?php echo $value['created_at']; ?></td>
            <td>
              <div class="btn-group mr-2">
                <a href="/help/users/<?php echo $value['id']; ?>/edit" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="/help/users/<?php echo $value['id']; ?>/delete" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure?')">Delete</a>
              </div>
            </td>
          </tr>
          <?php
        } ?>
      </tbody>
    </table>
  </div>
  <hr class="mb-4">
</div>
<?php include('_includes/footer.php'); ?>
