<?php include('_includes/header.php'); ?>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Users</h1>
</div>
<div class="col-md-8">
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Role</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>1,001</td>
          <td>Lorem</td>
          <td>Lorem</td>
        </tr>
        <tr>
          <td>1,002</td>
          <td>amet</td>
          <td>amet</td>
        </tr>
      </tbody>
    </table>
  </div>
  <hr class="mb-4">
</div>
<?php include('_includes/footer.php'); ?>
